name: SuperSmashCore
version: ${project.version}
description: The backbone of any super smash game.
author: George Bakewell
main: io.github.supersmashexperiments.ssc.Plugin
api-version: 1.13
depend: [ LibsDisguises ]
